openapi: 3.0.1
info:
  title: Example API
  version: 1.0.0
  description: An API example using remote references for schema definitions located at URLs.

servers:
  - url: https://api.example.com/v1

paths:
  /users:
    get:
      summary: Get list of users
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/c4rth/playground-openapi/refs/heads/main/schemas/user-schemas.yaml#/components/schemas/UserList'
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'https://raw.githubusercontent.com/c4rth/playground-openapi/refs/heads/main/schemas/user-schemas.yaml#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/c4rth/playground-openapi/refs/heads/main/schemas/user-schemas.yaml#/components/schemas/User'

  /users/{userId}:
    get:
      summary: Get user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/c4rth/playground-openapi/refs/heads/main/schemas/user-schemas.yaml#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/c4rth/playground-openapi/refs/heads/main/schemas/user-schemas.yaml#/components/schemas/Error'

components:
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: 'https://raw.githubusercontent.com/c4rth/playground-openapi/refs/heads/main/schemas/user-schemas.yaml#/components/schemas/Error'
