apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teama-service-ecommerce-v2-gtu
  description: service-ecommerce:20241206.2
  service-name: service-ecommerce
  service-version: '2'
  image-version: 'gtu2-20241206.2'
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
    sonarqube.org/project-key: YOUR_INSTANCE_NAME/service-ecommerce
spec:
  type: service
  lifecycle: GTU
  owner: group:default/team-a.o
  system: system-c
  providesApis:
  - teamb-api-product-v1.0.10
  consumesApis:
  - teama-ecommerce-v1.0.2
  - teama-ecommerce-v1.0.3