apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ecommerce-v1.0.1-snapshot
  description: Ecommerce API
  tags:
    - store
    - rest
  api-name: ecommerce
  api-version: 1.0.1-snapshot
  api-project: abcd
spec:
  type: openapi
  lifecycle: snapshot
  owner: backstage-team-a.O
  system: system-c
  definition:
    $text: https://github.com/c4rth/playground-openapi/blob/main/ecommerce/ecommerce-openapi-v1.0.1-snapshot.yaml