openapi: 3.0.1
info:
  title: Example API
  version: 1.1.0
  description: |
    # Description
    -  An API example using remote references for schema definitions located at URLs.
       - Modified 1
    -  An API example using remote references for schema definitions located at URLs.
       - Modified 2
    -  An API example using remote references for schema definitions located at URLs.
       - Modified 3
    -  An API example using remote references for schema definitions located at URLs.
       - Modified 4
    -  An API example using remote references for schema definitions located at URLs.
       - Modified 5
    ## EndOfDescription
  contact:
    name: daffy.duck@acme.com
    email: daffy.duck@acme.com
    url: https://acme.com

servers:
  - url: https://api.example-tst.com/v1

paths:
  /users:
    x-custom-info: Here's some custom information
    get:
      summary: Get list of users
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '../domains/product-schemas.yaml#/ProductList'
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../domains/product-schemas.yaml#/Product'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '../domains/product-schemas.yaml#/Product'

  /users/{userId}:
    x-custom-info: Here's some custom information
    get:
      summary: Get user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '../domains/product-schemas.yaml#/Product'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '../domains/product-schemas.yaml#/Error'

components:
  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '../domains/product-schemas.yaml#/Error'
