apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teama-service-dummy-v1-tst
  description: service-dummy:20250222.1
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
    service.depo.be/name: service-dummy
    service.depo.be/version: '1'
    service.depo.be/platform: 'onprem,cloud'
    service.depo.be/image: '20250222.1'
spec:
  type: service
  lifecycle: TST
  owner: group:default/team-a.o
  system: system-a
  providesApis:
  - teama-api-petstore-v1.0.19
  - api:local/dummy-provided.yaml
  consumesApis:
  - teama-api-backstage-v1.0.0
  - api:local/dummy-consumed.yaml
  dependsOn:
  - component:lib-core-v2.0.0
  - component:pipeline-v3
