apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teama-service-dummy-v1-tst
  description: service-dummy:20250222.1
  x-service:
    name: service-dummy
    version: '1'
    platform: onprem
    image: '20250222.1'
  service-name: service-dummy
  service-version: '1'
  service-platform: 'onprem,cloud'
  image-version: '20250222.1'
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
spec:
  type: service
  lifecycle: TST
  owner: team-a
  system: system-a
  providesApis:
  - teama-api-petstore-v1.0.19
  - api:local/dummy-provided.yaml
  consumesApis:
  - teama-api-backstage-v1.0.0
  - api:local/dummy-consumed.yaml
