apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teamb-service-dummy-v1-tst
  description: service-dummy:20250222.1
  service-name: service-dummy
  service-version: '1'
  service-platform: 'onprem,cloud'
  image-version: '20250222.1'
  devx-version: 'v5.5.0'
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
spec:
  type: service
  lifecycle: TST
  owner: group:default/team-b
  system: system-c
  providesApis:
  - teama-api-petstore-v1.0.19
  - api:local/dummy-provided.yaml
  consumesApis:
  - teama-api-backstage-v1.0.0
  - api:local/dummy-consumed.yaml
  dependsOn:
  - component:lib-core-v2.0.0
  - component:pipeline-v3
