apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-dummy-v1-tst
  description: service-dummy:20250222.1
  x-service:
    name: service-dummy
    version: '1'
    platform: onprem
    image: '20250222.1'
  service-name: service-dummy
  service-version: '1'
  service-platform: 'onprem,cloud'
  image-version: '20250222.1'
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
spec:
  type: service
  lifecycle: TST
  owner: team-b
  system: system-c
  providesApis:
  - api-petstore-v1.0.19
  - local:dummy-provided-local.yaml
  consumesApis:
  - api-backstage-v1.0.0
  - local:dummy-consumed-local.yaml
  - ecommerce-v1.0.5
