apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: teama-OperationSomethingFun-v1.0.0-P045
  description: OperationSomethingFun
  tags:
    - store
    - rest
  api-name: OperationSomethingFun
  api-version: 1.0.0-P045
  api-project: teama
  api-type: mca
spec:
  type: openapi
  lifecycle: release
  owner: group:default/team-a.o
  system: system-a
  definition:
    $text: https://github.com/c4rth/playground-openapi/blob/main/ecommerce/ecommerce-openapi-v1.0.0.yaml
