apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pipeline-v3
  description: pipeline version 3
  library-name: pipeline
  library-version: '3'
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
spec:
  type: library
  lifecycle: production
  owner: group:default/team-b
  system: system-b
