apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teama-service-ecommerce-v1-uat
  description: service-ecommerce:20241101.2
  service-name: service-ecommerce
  service-version: '1'
  image-version: 'uat1-20241101.2'
  devx-version: 'v4.5.0'
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
    sonarqube.org/project-key: YOUR_INSTANCE_NAME/service-ecommerce
spec:
  type: service
  lifecycle: UAT
  owner: group:default/team-a.o
  system: system-c
  providesApis:
  - teamb-api-product-v1.0.9
  consumesApis:
  - teama-ecommerce-v1.0.0
  - teama-ecommerce-v1.0.1