openapi: 3.0.1
info:
  title: Domain
  version: 1.0.0
  description: Sample Domain
  contact:
    name: daffy.duck@acme.com

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - email
    UserList:
      type: array
      items:
        $ref: '#/components/schemas/User'
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message