apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teamb-service-dummy-v1-gtu
  description: service-dummy:20250311.1
  service-name: service-dummy
  service-version: '1'
  service-platform: 'onprem,cloud'
  image-version: '20250311.1'
  devx-version: 'v4.5.0'
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
spec:
  type: service
  lifecycle: GTU
  owner: group:default/team-b
  system: system-c
  providesApis:
  - api:local/dummy-provided.yaml
  consumesApis:
  - api:local/dummy-consumed.yaml
