apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teamb-service-dummy-v1-gtu
  description: service-dummy:20250311.1
  annotations:
    dev.azure.com/project-repo: java-playground/java-playground
    service.depo.be/name: service-dummy
    service.depo.be/version: '1'
    service.depo.be/platform: 'onprem,cloud'
    service.depo.be/image: '20250311.1'
spec:
  type: service
  lifecycle: GTU
  owner: group:default/team-b
  system: system-c
  providesApis:
  - api:local/dummy-provided.yaml
  consumesApis:
  - api:local/dummy-consumed.yaml
  dependsOn:
  - component:lib-core-v1.0.0
  - component:pipeline-v2
  - component:cicd-pipeline-templates-vfeature/custom-pipeline-version-to-test
