apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-product-v1.0.0
  description: Product API
  tags:
    - store
    - rest
  api-name: api-product
  api-version: v1.0.0
  api-project: wxyz
spec:
  type: openapi
  lifecycle: experimental
  owner: team-c
  definition:
    $text: https://github.com/c4rth/playground-openapi/blob/main/products/api-product-v1.0.0.yaml